name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # Run CI checks first - release only if these pass
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Run go vet
        run: go vet ./...

      - name: Check formatting
        run: |
          go install mvdan.cc/gofumpt@latest
          test -z "$(gofumpt -l .)"

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Run tests
        run: go test -race -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          files: ./coverage.out
          fail_ci_if_error: false

  ci-build:
    name: CI Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Build binary
        run: go build -o jobster ./cmd/jobster

      - name: Test binary
        run: ./jobster --version

  # Semantic Release determines if we need a release (only runs if CI passes)
  semantic-release:
    needs: [lint, test, ci-build]
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
      new-release-version: ${{ steps.semantic.outputs.new-release-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Run semantic-release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git

  # Build binaries only if semantic-release created a new release
  build:
    name: Build Release Binaries
    needs: semantic-release
    if: needs.semantic-release.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: v${{ needs.semantic-release.outputs.new-release-version }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: v${{ needs.semantic-release.outputs.new-release-version }}
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')

          go build -ldflags "-X main.version=${VERSION} -X main.commit=${COMMIT} -X main.buildTime=${BUILD_TIME}" \
            -o jobster-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/jobster

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jobster-${{ matrix.goos }}-${{ matrix.goarch }}
          path: jobster-${{ matrix.goos }}-${{ matrix.goarch }}

  # Upload binaries to the release created by semantic-release
  upload-assets:
    name: Upload Release Assets
    needs: [semantic-release, build]
    if: needs.semantic-release.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release
          find artifacts -type f -name "jobster-*" -exec mv {} release/ \;
          cp systemd/*.service release/
          cp scripts/*.sh release/

          # Generate checksums
          cd release
          sha256sum jobster-* *.service *.sh > SHA256SUMS

      - name: Upload assets to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ needs.semantic-release.outputs.new-release-version }} \
            release/* \
            --clobber
